ddragon_version: 16.13.1
minimap:
  x0: 1620
  y0: 812
  x1: 1898
  y1: 1068
train_imgsz: 256
champions:
- Yorick
- Sejuani
- Smolder
- Ziggs
- Nautilus
- Camille
- Pantheon
- Galio
- MissFortune
- Leona
teams:
- KT
- T1
adc_champ:
  KT: Ziggs
  T1: MissFortune
support_champ: &id001
  KT: Yorick
  T1: Camille
support_player:
  KT: PerfecT
  T1: Doran
duel_champ: *id001
duel_player:
  KT: PerfecT
  T1: Doran
